const rides=window.ATTRACTIONS||[];
const API_BASE='/europa-park-planner-api';
let activeProfile=null,selections={},pending=[],fearFilter='all',typeFilter='all',query='',cloudVersion=-1,eventStream=null,reconnectTimer=null,syncChain=Promise.resolve(),galleryRide=null,galleryIndex=0;
const fearColors=['','#31a66d','#67a741','#e1a218','#e46b28','#d83b4f'];
const areaNames={Abenteuerland:'ארץ ההרפתקאות',Deutschland:'גרמניה',England:'אנגליה',Frankreich:'צרפת',Griechenland:'יוון','Grimms Märchenwald':'יער האגדות של גרים',Holland:'הולנד',Irland:'אירלנד',Island:'איסלנד',Italien:'איטליה',Kroatien:'קרואטיה','Königreich der Minimoys':'ממלכת המינימויים',Luxemburg:'לוקסמבורג',Monaco:'מונקו',Portugal:'פורטוגל',Russland:'רוסיה',Schweiz:'שווייץ',Skandinavien:'סקנדינביה',Spanien:'ספרד','Österreich':'אוסטריה'};
const $=id=>document.getElementById(id);
function cacheKey(kind){return activeProfile?`europa-profile-${activeProfile.id}-${kind}`:''}
function loadLocal(kind,fallback){try{return JSON.parse(localStorage.getItem(cacheKey(kind)))||fallback}catch{return fallback}}
function saveLocal(){if(activeProfile)localStorage.setItem(cacheKey('selections'),JSON.stringify(selections));updateSummary()}
function savePending(){if(activeProfile)localStorage.setItem(cacheKey('pending'),JSON.stringify(pending))}
function selected(ride){return Boolean(selections[ride])}
function esc(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function ruleHe(value,kind){if(!value)return'';if(kind==='age'){let m=value.match(/^(\d+)\+ Jahre$/);if(m)return`מגיל ${m[1]}`;m=value.match(/^unter (\d+) Jahren nur in Begleitung eines Erwachsenen$/);if(m)return`מתחת לגיל ${m[1]}: רק בליווי מבוגר`;return value.replace('bis','עד').replace('Jahre','שנים')}if(kind==='height'){let m=value.match(/^(\d+)\+ cm$/);if(m)return`מ־${m[1]} ס״מ`;m=value.match(/^unter (\d+) cm nur in Begleitung eines Erwachsenen$/);if(m)return`מתחת ל־${m[1]} ס״מ: רק בליווי מבוגר`;return value.replace('bis','עד').replace('cm','ס״מ')}if(kind==='duration')return value.replace('Min.','דקות');return value}
function areaHe(value){return areaNames[value]||value}
function specs(ride){return [['אזור',areaHe(ride.area)],['גיל',ruleHe(ride.age,'age')],['גובה',ruleHe(ride.height_rule,'height')],['משך',ruleHe(ride.duration,'duration')],['מהירות',ride.speed]].filter(x=>x[1]).map(x=>`<span class="spec"><strong>${x[0]}:</strong>${esc(x[1])}</span>`).join('')}
function fearDots(score){return Array.from({length:5},(_,i)=>`<span class="fear-dot${i<score?' on':''}"></span>`).join('')}
function matches(ride){const text=`${ride.name} ${ride.area} ${areaHe(ride.area)} ${ride.description} ${ride.type}`.toLowerCase();return(!query||text.includes(query))&&(typeFilter==='all'||ride.type===typeFilter)&&(fearFilter==='all'||fearFilter==='low'&&ride.fear<=2||fearFilter==='medium'&&ride.fear===3||fearFilter==='high'&&ride.fear>=4)}
function render(){const visible=rides.filter(matches);$('resultCount').textContent=`מציג ${visible.length} מתוך ${rides.length}`;$('emptyState').classList.toggle('visible',!visible.length);$('rideList').innerHTML=visible.map(ride=>`<article class="ride-card" id="ride-${ride.id}" data-ride="${ride.id}" style="--fear-color:${fearColors[ride.fear]}">
  <div class="ride-photo"><img src="${ride.image}" alt="${esc(ride.name)} בפארק אירופה" loading="lazy" width="720" height="405"><span class="ride-index">${String(rides.indexOf(ride)+1).padStart(3,'0')}</span><a class="photo-credit" href="${ride.source}" target="_blank" rel="noopener">צילום ומידע: Europa‑Park ↗</a></div>
  <div class="ride-info"><div class="meta"><span class="tag">${esc(areaHe(ride.area)||'Europa‑Park')}</span><span class="tag type-tag">${esc(ride.type)}</span></div><h3>${esc(ride.name)}</h3><p class="description">${esc(ride.description)}</p><div class="fear-box"><div class="fear-score">פחד ${ride.fear}/5<div class="fear-dots">${fearDots(ride.fear)}</div></div><div class="fear-note">${esc(ride.fear_note)}</div></div><div class="specs">${specs(ride)}</div><div class="action-row"><a class="video-link" href="${ride.youtube}" target="_blank" rel="noopener noreferrer" title="${esc(ride.youtube_title)} — ${esc(ride.youtube_channel)}" aria-label="צפייה בסרטון YouTube של ${esc(ride.name)}"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M23 7.1a3 3 0 0 0-2.1-2.1C19 4.5 12 4.5 12 4.5s-7 0-8.9.5A3 3 0 0 0 1 7.1C.5 9 .5 12 .5 12s0 3 .5 4.9A3 3 0 0 0 3.1 19c1.9.5 8.9.5 8.9.5s7 0 8.9-.5a3 3 0 0 0 2.1-2.1c.5-1.9.5-4.9.5-4.9s0-3-.5-4.9ZM9.7 15.3V8.7l5.8 3.3-5.8 3.3Z"/></svg><span>סרטון</span></a><button class="gallery-btn" type="button" data-gallery="${ride.id}" aria-label="פתיחת גלריית התמונות של ${esc(ride.name)}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m4 17 5-4 3 3 3-2 5 4"/></svg><span>גלריית תמונות</span></button><button class="gallery-btn map-location-btn" type="button" data-map-location="${ride.id}" aria-label="הצגת ${esc(ride.name)} במפה"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg><span>מיקום במפה</span></button></div></div>
  <div class="choices" aria-label="הבחירה שלך עבור ${esc(ride.name)}"><label class="choice"><input type="checkbox" data-ride="${ride.id}" aria-label="אני רוצה לעלות על ${esc(ride.name)}" ${selected(ride.id)?'checked':''}><span class="check-ui"><svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 4 4L19 6"/></svg></span><span class="choice-name">אני רוצה לעלות</span></label></div></article>`).join('')}
function chosenGroups(){const groups=new Map();rides.filter(r=>selected(r.id)).forEach(ride=>{const country=areaHe(ride.area)||'אזור אחר';if(!groups.has(country))groups.set(country,[]);groups.get(country).push(ride)});return [...groups.entries()].sort(([a],[b])=>a.localeCompare(b,'he')).map(([country,items])=>[country,items.sort((a,b)=>a.name.localeCompare(b.name,'en'))])}
function renderChosen(){const groups=chosenGroups(),count=groups.reduce((sum,[,items])=>sum+items.length,0);$('chosenCount').textContent=count;$('chosenList').innerHTML=count?groups.map(([country,items])=>`<section class="chosen-country"><div class="chosen-country-head"><h3>${esc(country)}</h3><span>${items.length} ${items.length===1?'מתקן':'מתקנים'}</span></div><div class="chosen-country-grid">${items.map(ride=>`<article class="chosen-item"><img src="${ride.image}" alt="" loading="lazy"><div class="chosen-copy"><strong>${esc(ride.name)}</strong><span>${esc(ride.type)} · פחד ${ride.fear}/5</span></div><button class="chosen-remove" type="button" data-remove-choice="${ride.id}" aria-label="הסרת ${esc(ride.name)} מרשימת מה בחרתי">×</button></article>`).join('')}</div></section>`).join(''):`<div class="chosen-empty">${activeProfile?'לא בחרת עדיין מתקנים. אפשר לסמן מתקנים בקטלוג למטה.':'לאחר הזנת שם, הבחירות שלך יופיעו כאן.'}</div>`}
function updateSummary(){const count=rides.filter(r=>selected(r.id)).length,percent=rides.length?Math.round(count/rides.length*100):0;$('personalCount').textContent=count;$('progressBar').style.width=`${percent}%`;$('progressCount').textContent=`${count} מתוך ${rides.length} בחירות`;$('progressTitle').textContent=!count?'עוד לא התחלת':count===rides.length?'בחרת הכול! 🎉':percent>65?'כמעט סיימת':'הרשימה שלך מתגבשת';renderChosen()}
function showToast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1600)}
function setSync(mode,text){$('syncState').classList.toggle('syncing',mode==='syncing');$('syncState').classList.toggle('offline',mode==='offline');$('syncText').textContent=text}
function syncCheckboxes(){document.querySelectorAll('#rideList input[type="checkbox"]').forEach(input=>{input.checked=selected(input.dataset.ride)})}
async function api(path,options={}){const response=await fetch(`${API_BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})},cache:'no-store'});const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error||'sync_failed'),{status:response.status,data});return data}
function applyCloud(data){if(!data||data.id!==activeProfile?.id||typeof data.version!=='number'||data.version<cloudVersion)return;cloudVersion=data.version;selections={...(data.selections||{})};pending.forEach(change=>{selections[change.ride]=change.checked});saveLocal();syncCheckboxes();setSync('online','הרשימה מסונכרנת בזמן אמת בין המכשירים')}
function queueSelection(ride,checked){pending=pending.filter(item=>item.ride!==ride);pending.push({ride,checked});savePending()}
async function pushSelection(change){if(!activeProfile)return;setSync('syncing','שומר בכל המכשירים…');try{const data=await api('/select',{method:'POST',body:JSON.stringify({profileId:activeProfile.id,...change})});pending=pending.filter(item=>item.ride!==change.ride);savePending();applyCloud(data);showToast('נשמר וסונכרן')}catch{setSync('offline','אין חיבור — השינוי שמור ויישלח כשנחזור לרשת');scheduleReconnect()}}
function openEvents(){if(eventStream)eventStream.close();if(!activeProfile)return;eventStream=new EventSource(`${API_BASE}/events?profile=${encodeURIComponent(activeProfile.id)}`);eventStream.onopen=()=>setSync('online','הרשימה מסונכרנת בזמן אמת בין המכשירים');eventStream.onmessage=event=>{try{applyCloud(JSON.parse(event.data))}catch{}};eventStream.onerror=()=>setSync('offline','מנסה להתחבר מחדש לסנכרון…')}
function scheduleReconnect(){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(initializeSync,4000)}
async function initializeSync(){if(!activeProfile)return;setSync('syncing','מתחבר לרשימה שלך…');try{for(const change of [...pending])await pushSelection(change);openEvents()}catch{setSync('offline','אין חיבור — נשמר זמנית במכשיר');scheduleReconnect()}}
async function loadProfile(name){$('nameError').textContent='';setSync('syncing','פותח את הרשימה שלך…');try{const profile=await api('/profile',{method:'POST',body:JSON.stringify({name})});activeProfile=profile;cloudVersion=profile.version;selections={...(profile.selections||{})};pending=loadLocal('pending',[]);pending.forEach(change=>{selections[change.ride]=change.checked});localStorage.setItem('europa-last-name',profile.name);localStorage.setItem('europa-active-profile',JSON.stringify({id:profile.id,name:profile.name}));$('currentName').textContent=profile.name;$('switchName').textContent=`${profile.name} · החלפת שם`;$('switchName').hidden=false;$('nameGate').hidden=true;render();updateSummary();focusRequestedRide();initializeSync()}catch{$('nameError').textContent='לא הצלחנו לפתוח את הרשימה. בדקו את החיבור ונסו שוב.';setSync('offline','לא ניתן להתחבר כרגע')}}
function switchName(){if(eventStream)eventStream.close();clearTimeout(reconnectTimer);activeProfile=null;selections={};pending=[];cloudVersion=-1;$('switchName').hidden=true;$('nameGate').hidden=false;$('nameInput').focus();setSync('syncing','יש להזין שם כדי להתחבר…')}
function openGallery(id){galleryRide=rides.find(r=>r.id===id);if(!galleryRide)return;galleryIndex=0;$('galleryTitle').textContent=galleryRide.name;$('galleryModal').showModal();updateGallery()}
function galleryImages(){return galleryRide?.gallery?.length?galleryRide.gallery:[galleryRide?.image].filter(Boolean)}
function updateGallery(){const images=galleryImages(),src=images[galleryIndex];$('galleryImage').src=src;$('galleryImage').alt=`${galleryRide.name} — תמונה ${galleryIndex+1}`;$('galleryCounter').textContent=`${galleryIndex+1} מתוך ${images.length}`;$('galleryThumbs').innerHTML=images.map((image,i)=>`<button class="gallery-thumb${i===galleryIndex?' active':''}" type="button" data-gallery-index="${i}" aria-label="תמונה ${i+1}"><img src="${image}" alt="" loading="lazy"></button>`).join('');$('galleryPrev').hidden=images.length<2;$('galleryNext').hidden=images.length<2}
function moveGallery(delta){const images=galleryImages();galleryIndex=(galleryIndex+delta+images.length)%images.length;updateGallery()}
function focusRideOnMap(id){window.location.href=`map.html?ride=${encodeURIComponent(id)}`}
function focusRequestedRide(){const id=new URLSearchParams(location.search).get('ride');if(!id)return;query='';$('searchInput').value='';render();requestAnimationFrame(()=>$(`ride-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'}))}
function buildPrintRoute(){const groups=chosenGroups(),count=groups.reduce((sum,[,items])=>sum+items.length,0);if(!activeProfile||!count)return false;const date=new Intl.DateTimeFormat('he-IL',{dateStyle:'long'}).format(new Date());$('printRoute').innerHTML=`<header class="print-title"><h1>המסלול של ${esc(activeProfile.name)} ב‑Europa‑Park</h1><p>תכנון מתקנים לפי מדינות</p></header><div class="print-summary"><strong>${count} מתקנים ב־${groups.length} מדינות ואזורים</strong><span>נוצר בתאריך ${esc(date)}</span></div>${groups.map(([country,items])=>`<section class="print-country"><h2>${esc(country)} · ${items.length} ${items.length===1?'מתקן':'מתקנים'}</h2><table><thead><tr><th>#</th><th>מתקן</th><th>סוג</th><th>רמת פחד</th><th>גובה / גיל</th></tr></thead><tbody>${items.map((ride,index)=>`<tr><td>${index+1}</td><td><strong dir="ltr">${esc(ride.name)}</strong></td><td>${esc(ride.type)}</td><td>${ride.fear}/5</td><td>${esc([ruleHe(ride.height_rule,'height'),ruleHe(ride.age,'age')].filter(Boolean).join(' · ')||'—')}</td></tr>`).join('')}</tbody></table></section>`).join('')}<footer class="print-footer">Europa Crew · המסלול האישי שלי בפארק אירופה</footer>`;return true}
function saveRoutePdf(){if(!buildPrintRoute()){showToast('צריך לבחור לפחות מתקן אחד לפני יצירת PDF');return}const oldTitle=document.title;document.title=`Europa-Park - המסלול של ${activeProfile.name}`;$('printRoute').setAttribute('aria-hidden','false');window.addEventListener('afterprint',()=>{document.title=oldTitle;$('printRoute').setAttribute('aria-hidden','true')},{once:true});window.print()}
$('nameForm').addEventListener('submit',event=>{event.preventDefault();const name=$('nameInput').value.trim().replace(/\s+/g,' ');if(name.length<2){$('nameError').textContent='נא להזין שם בן שתי אותיות לפחות.';return}loadProfile(name)});
$('switchName').addEventListener('click',switchName);
$('rideList').addEventListener('change',event=>{const input=event.target.closest('input[type="checkbox"]');if(!input||!activeProfile)return;const change={ride:input.dataset.ride,checked:input.checked};selections[change.ride]=change.checked;queueSelection(change.ride,change.checked);saveLocal();syncChain=syncChain.then(()=>pushSelection(change))});
$('rideList').addEventListener('click',event=>{const galleryButton=event.target.closest('[data-gallery]');if(galleryButton)openGallery(galleryButton.dataset.gallery);const mapButton=event.target.closest('[data-map-location]');if(mapButton)focusRideOnMap(mapButton.dataset.mapLocation)});
$('chosenList').addEventListener('click',event=>{const button=event.target.closest('[data-remove-choice]');if(!button||!activeProfile)return;const change={ride:button.dataset.removeChoice,checked:false};selections[change.ride]=false;queueSelection(change.ride,false);saveLocal();syncCheckboxes();syncChain=syncChain.then(()=>pushSelection(change))});
$('pdfBtn').addEventListener('click',saveRoutePdf);
$('searchInput').addEventListener('input',event=>{query=event.target.value.trim().toLowerCase();render()});
$('typeSelect').addEventListener('change',event=>{typeFilter=event.target.value;render()});
document.querySelector('.fear-filters').addEventListener('click',event=>{const button=event.target.closest('[data-fear]');if(!button)return;fearFilter=button.dataset.fear;document.querySelectorAll('.fear-btn').forEach(x=>x.classList.toggle('active',x===button));render()});
$('resetBtn').addEventListener('click',async()=>{if(!activeProfile||!Object.values(selections).some(Boolean)||!confirm(`לאפס את כל הבחירות ברשימה של ${activeProfile.name} בכל המכשירים?`))return;setSync('syncing','מאפס את הרשימה…');try{const data=await api('/reset',{method:'POST',body:JSON.stringify({profileId:activeProfile.id,confirm:'reset'})});pending=[];savePending();applyCloud(data);showToast('הרשימה אופסה בכל המכשירים')}catch{setSync('offline','האיפוס נכשל — נסו שוב כשיש חיבור')}});
$('galleryClose').addEventListener('click',()=>$('galleryModal').close());$('galleryPrev').addEventListener('click',()=>moveGallery(-1));$('galleryNext').addEventListener('click',()=>moveGallery(1));$('galleryThumbs').addEventListener('click',event=>{const button=event.target.closest('[data-gallery-index]');if(button){galleryIndex=Number(button.dataset.galleryIndex);updateGallery()}});$('galleryModal').addEventListener('click',event=>{if(event.target===$('galleryModal'))$('galleryModal').close()});
const types=[...new Set(rides.map(r=>r.type))].sort((a,b)=>a.localeCompare(b,'he'));$('typeSelect').insertAdjacentHTML('beforeend',types.map(t=>`<option>${t}</option>`).join(''));$('totalRides').textContent=`/ ${rides.length}`;$('heroCount').textContent=rides.length;$('nameInput').value=localStorage.getItem('europa-last-name')||'';render();updateSummary();focusRequestedRide();
